name: medusa-admin
region: fra
static_sites:
- name: admin
  github:
    repo: TheBigRigZA/medusa-admin
    branch: main
    deploy_on_push: true
  source_dir: /
  output_dir: /
  index_document: index.html
<<<<<<< HEAD
  catchall_document: index.html
=======
  error_document: index.html
  routes:
  - path: /*
    rewrite_path: /index.html
>>>>>>> d37206d93441bd2cad8432849762355d92dbfd31
